# Generated by Django 4.1.5 on 2023-01-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_HABBIT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='name',
            new_name='Title',
        ),
    ]
