# Generated by Django 4.1.5 on 2023-01-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_HABBIT', '0002_rename_name_habit_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='type',
            field=models.CharField(choices=[('yesorno', 'Yes or No'), ('measurable', 'Measurable')], max_length=10),
        ),
        migrations.AlterField(
            model_name='habit',
            name='value',
            field=models.CharField(blank=True, choices=[('yesorno', 'Yes or No'), ('measurable', 'Measurable')], max_length=10, null=True),
        ),
    ]
