# Generated by Django 4.1.5 on 2023-01-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_HABBIT', '0004_alter_habit_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
        migrations.AddField(
            model_name='habit',
            name='Question',
            field=models.CharField(default='Default value', max_length=400),
        ),
        migrations.AddField(
            model_name='habit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
