# Generated by Django 4.1.5 on 2023-01-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_HABBIT', '0005_remove_habit_description_habit_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='Question',
            field=models.CharField(default='', max_length=400),
        ),
    ]
