# Generated by Django 4.1.5 on 2023-01-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_HABBIT', '0006_alter_habit_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habit',
            new_name='Habitmodel',
        ),
    ]
