# Generated by Django 4.1.5 on 2023-01-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_HABBIT', '0008_rename_type_habitmodel_habit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmodel',
            name='target',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
