# Generated by Django 4.1.5 on 2023-01-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_HABBIT', '0010_habitresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='habitresponse',
            name='target',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='habitresponse',
            name='value',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True),
        ),
    ]
