# Generated by Django 4.1.5 on 2023-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_HABBIT', '0011_remove_habitresponse_user_habitresponse_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitresponse',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
