# Generated by Django 4.1.5 on 2023-01-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_HABBIT', '0013_alter_habitresponse_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitmodel',
            name='value',
        ),
    ]
